/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm"
import * as bcrypt from 'bcrypt';
import * as dotenv from 'dotenv';
const path = `${__dirname}/../../.env`;
dotenv.config({ path: path });

export class UserSeeding1691742993387 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        const saltRounds = parseInt(process.env.BCRYPT_SALT_ROUNDS || '10', 10);
        
        const usersToSeed= [
            {
                department_id: 1,
                office_id: 1,
                position_id: 1,
                title_id: 1,
                role_id: 1,
                kh_name: 'Nara',
                en_name: 'Nara',
                username: 'nara',
                email: 'nara@gmail.com',
                phone: '016838248',
                password: '123456',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 1,
                position_id: 3,
                title_id: 2,
                role_id: 2,
                kh_name: 'ឆាន រត្នា',
                en_name: 'CHHAN RATHANA',
                username: 'chanrathana',
                email: 'chanrathana@gmail.com',
                phone: '081752598',
                password: '081752598',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 1,
                position_id: 4,
                title_id: 3,
                role_id: 2,
                kh_name: 'នួន សុគន្ធា',
                en_name: 'NOUN SOKUNTHEA',
                username: 'nounsokunthea',
                email: 'nounsokunthea@gmail.com',
                phone: '016444875',
                password: '016444875',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 1,
                position_id: 4,
                title_id: 2,
                role_id: 2,
                kh_name: 'ខួច គឿន',
                en_name: 'KHOUCH KOEUN',
                username: 'khouchkoeun',
                email: 'khouchkoeun@gmail.com',
                phone: '0965416704',
                password: '0965416704',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 1,
                position_id: 4,
                title_id: 3,
                role_id: 2,
                kh_name: 'អ៊ី ស្រីរ័ត្ន',
                en_name: 'E SREYROTH',
                username: 'esreyroth',
                email: 'esreyroth@gmail.com',
                phone: '012270197',
                password: '012270197',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 5,
                title_id: 2,
                role_id: 4,
                kh_name: 'ឈឹម សុធារិទ្ធ',
                en_name: 'CHHEM SOKTHEARITH',
                username: 'chhemsokthearith',
                email: 'chhemsokthearith@gmail.com',
                phone: '0966778779',
                password: '0966778779',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 5,
                title_id: 2,
                role_id: 2,
                kh_name: 'ស៊ាត សុវណ្ណ',
                en_name: 'SEAT SOVANN',
                username: 'seatsovann',
                email: 'seatsovann@gmail.com',
                phone: '0767220007',
                password: '0767220007',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 5,
                title_id: 2,
                role_id: 2,
                kh_name: 'ឡេង គីមលាំង',
                en_name: 'LENG KIMLANG',
                username: 'lengkimlang',
                email: 'lengkimlang@gmail.com',
                phone: '093416617',
                password: '093416617',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 7,
                title_id: 2,
                role_id: 1,
                kh_name: 'អន ស៊ីដេត',
                en_name: 'ON SIDETH',
                username: 'onsideth',
                email: 'onsideth@gmail.com',
                phone: '099679501',
                password: '099679501',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ព្រឿង ស៊ីម៉េង',
                en_name: 'PREOUNG SIMENG',
                username: 'preoungsimeng',
                email: 'preoungsimeng@gmail.com',
                phone: '0977027294',
                password: '0977027294',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 8,
                title_id: 3,
                role_id: 6,
                kh_name: 'ឃុន ស្រីល័ក្ខ',
                en_name: 'KHUN SREYLEAK',
                username: 'khunsreyleak',
                email: 'khunsreyleak@gmail.com',
                phone: '089783769',
                password: '089783769',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 8,
                title_id: 3,
                role_id: 6,
                kh_name: 'និន មួយទៀង',
                en_name: 'NEN MOUYTEANG',
                username: 'nenmouyteang',
                email: 'nenmouyteang@gmail.com',
                phone: '099208875',
                password: '099208875',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 2,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'សុកាន សុវិជ្ជា',
                en_name: 'SOKAN SOVICHEA',
                username: 'sokansovichea',
                email: 'sokansovichea@gmail.com',
                phone: '089251834',
                password: '089251834',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 5,
                title_id: 2,
                role_id: 3,
                kh_name: 'យឿន សត្យា',
                en_name: 'YOEUN SETHYA',
                username: 'yoeunsethya',
                email: 'yoeunsethya@gmail.com',
                phone: '070454047',
                password: '070454047',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 6,
                title_id: 2,
                role_id: 4,
                kh_name: 'ខាន់ ណារិទ្ធ',
                en_name: 'KHAN NARITH',
                username: 'khannarith',
                email: 'khannarith@gmail.com',
                phone: '098266108',
                password: '098266108',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ចិន សុផល',
                en_name: 'CHEN SOPHAL',
                username: 'chensophal',
                email: 'chensophal@gmail.com',
                phone: '0998844644',
                password: '0998844644',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ឆាន វីរៈបុត្រ',
                en_name: 'CHHAN VIRAKBUTH',
                username: 'chhanvirakbuth',
                email: 'chhanvirakbuth@gmail.com',
                phone: '0969640495',
                password: '0969640495',
                about: 'Nothing'
            },
            
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'តាំង អេងឃុន',
                en_name: 'TAING ENGKHUN',
                username: 'taingengkhun',
                email: 'taingengkhun@gmail.com',
                phone: '087999938',
                password: '087999938',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'វង្ស សុខសំណាង',
                en_name: 'VONG SOKSAMNANG',
                username: 'vongsoksamnang',
                email: 'vongsoksamnang@gmail.com',
                phone: '071963389',
                password: '071963389',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'យីម ឃ្លោក',
                en_name: 'YIM KLOK',
                username: 'yimklok',
                email: 'yimklok@gmail.com',
                phone: '0977779688',
                password: '0977779688',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'គីម សុណេន',
                en_name: 'KIM SONEN',
                username: 'kimsoknen',
                email: 'kimsoknen@gmail.com',
                phone: '0965175578',
                password: '0965175578',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'កយ ព្រីយ៉ែល',
                en_name: 'KAY BRIYEL',
                username: 'kaybriyel',
                email: 'kaybriyel@gmail.com',
                phone: '086616257',
                password: '086616257',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 3,
                role_id: 6,
                kh_name: 'វ៉ន សុខអ៊ីម',
                en_name: 'VORN SOKIM',
                username: 'vornsokim',
                email: 'vornsokim@gmail.com',
                phone: '093563489',
                password: '093563489',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'យឿន វិទូ',
                en_name: 'YOEUN VITU',
                username: 'yoeunvitu',
                email: 'yoeunvitu@gmail.com',
                phone: '015768811',
                password: '015768811',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 3,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ថាន់ សុខខេន',
                en_name: 'THANN SOK KHEN',
                username: 'thannsokkhen',
                email: 'thannsokkhen@gmail.com',
                phone: '077390651',
                password: '077390651',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 5,
                title_id: 2,
                role_id: 3,
                kh_name: 'ហ៊ន គឹមហាន',
                en_name: 'HOUN KIMHAN',
                username: 'hounkimhan',
                email: 'hounkimhan@gmail.com',
                phone: '0967732415',
                password: '0967732415',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 6,
                title_id: 3,
                role_id: 4,
                kh_name: 'លី សុខឡា',
                en_name: 'LY SOKLA',
                username: 'lysokla',
                email: 'lysokla@gmail.com',
                phone: '086635106',
                password: '086635106',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'បូរ៉ាត មុនីរតន៍',
                en_name: 'BORATH MUNIROTH',
                username: 'borathmuniroth',
                email: 'borathmuniroth@gmail.com',
                phone: '012961111',
                password: '012961111',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'បូរ ពិសី',
                en_name: 'BO PISEY',
                username: 'bopisey',
                email: 'bopisey@gmail.com',
                phone: '0964737335',
                password: '0964737335',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'គង់ ចន្ថា',
                en_name: 'KUNG CHANTHA',
                username: 'kungchantha',
                email: 'kungchantha@gmail.com',
                phone: '069345445',
                password: '069345445',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'លី ឡាយ',
                en_name: 'LY LAY',
                username: 'lylay',
                email: 'lylay@gmail.com',
                phone: '093555970',
                password: '093555970',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 3,
                role_id: 6,
                kh_name: 'សូ ធានី',
                en_name: 'SO THEANY',
                username: 'sotheavy',
                email: 'sotheavy@gmail.com',
                phone: '061254560',
                password: '061254560',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'អាង ម៉េងអ័ង',
                en_name: 'ANG MENGONG',
                username: 'angmenggong',
                email: 'angmenggong@gmail.com',
                phone: '0962567090',
                password: '0962567090',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ទូច ហៀងងួន',
                en_name: 'TOUCH HEANGNGOUN',
                username: 'touchheangngoun',
                email: 'touchheangngoun@gmail.com',
                phone: '0962219158',
                password: '0962219158',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'ឈឿន វឌ្ឍនៈ',
                en_name: 'CHHOEUN VATHANAK',
                username: 'chhoeunvathanak',
                email: 'chhoeunvathanak@gmail.com',
                phone: '0965372263',
                password: '0965372263',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 3,
                role_id: 6,
                kh_name: 'លី ស៊ីវហ៊ួរ',
                en_name: 'LY SIVHOUR',
                username: 'lysivhour',
                email: 'lysivhour@gmail.com',
                phone: '095838111',
                password: '095838111',
                about: 'Nothing'
            },
            {
                department_id: 2,
                office_id: 4,
                position_id: 8,
                title_id: 2,
                role_id: 6,
                kh_name: 'វុទ្ធី គីមហុង',
                en_name: 'VUTHY KIMHONG',
                username: 'vuthykimhong',
                email: 'vuthykimhong@gmail.com',
                phone: '0967106345',
                password: '0967106345',
                about: 'Nothing'
            },

        ];

        // Insert users
        for (const user of usersToSeed) {
            const hashedPassword = await bcrypt.hash(user.password, saltRounds);
            await queryRunner.query(
            `INSERT INTO "users"("department_id", "office_id", "position_id", "title_id", "role_id", "kh_name", "en_name", "username", "email", "phone", "password", "about") VALUES (${user.department_id}, ${user.office_id}, ${user.position_id}, ${user.title_id}, ${user.role_id}, '${user.kh_name}', '${user.en_name}', '${user.username}', '${user.email}', '${user.phone}', '${hashedPassword}', '${user.about}')`
            );
        }

        
    }

    // eslint-disable-next-line @typescript-eslint/no-empty-function
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "users_role"`);
    }

}
